### ISSUE TITLE
New tag/release required for node16 bump.

### ISSUE THREAD

**Issue by hoivikaj** [sushichop/action-repository-permission#27]
It appears the bump to node 16 in commit 414acc1 took place after your most recent tag/release - so its not possible to use this action via node 16 without calling the main branch.

As this is a major node bump, this most likely qualifies for a v2 tag release.

**Comment by sushichop** [comment]
@hoivikaj 
Thanks for letting me know.

Node.js 16 seems to be already in the maintenance period.
So I want to bump up to Node.js 18 at once with a v2 tag release🙂
https://github.com/nodejs/release#release-schedule

**Comment by sushichop** [comment]
> Node.js 16 seems to be already in the maintenance period.
> So I want to bump up to Node.js 18 at once with a v2 tag release🙂
> https://github.com/nodejs/release#release-schedule

I have created a PR for this. #28

**Comment by sushichop** [comment]
Whoops! Node.js 18 doesn't seem to be supported by GitHub Actions yet...
I'll change to Node.js 16.

> Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node18' is not supported, use 'docker', 'node12' or 'node16' instead.')

**Comment by sushichop** [comment]
I have released [action-repository-permission@v2](https://github.com/sushichop/action-repository-permission/releases/tag/v2.0.0) that supports only Node.js 16 or later.
Then I'm closing this issue since it has fixed by #29.

Thanks.
